### ISSUE TITLE
Funky Zero length field name error.

### ISSUE THREAD

**Issue by Ryanb58** [khamidou/lptrace#6]
```
Traceback (most recent call last):
  File "lptrace", line 116, in <module>
    main()
  File "lptrace", line 112, in main
    strace(pid)
  File "lptrace", line 50, in strace
    runfile(pid, trace_code)
  File "lptrace", line 39, in runfile
    cmd = 'execfile(\\"{}\\")'.format(name)
ValueError: zero length field name in forma
```

I went through the instructions in your README and this error was returned. Any thoughts?

**Comment by khamidou** [comment]
Hi there! Thanks for taking the time to fill out a bug. This could be an issue for old versions of Python. Are you on Python 2.6 by any chance?

**Comment by Ryanb58** [comment]
@khamidou I am actually running python 2.7.2.
